### ISSUE TITLE
Scroll position moves on save

### ISSUE THREAD

**Issue by Rowno** [sindresorhus/editorconfig-sublime#27]
A recent update added a bug that causes the editor to scroll up 1 line every time the editor is saved. I think 2e68c0ca036e29e148771518ee00c3288b251799 is causing it because I'm pretty sure this wasn't happening last week.

I'm using Sublime Text 3 on Mac OSX 10.9 / Ubuntu 13.10.

**Comment by drguiom** [comment]
I know this is a really old post but I can't find an answer as to how this has been fixed.

Every time I save a file (Mac OSX 10.13.6 and Sublime Text 3.1.1) the cursor position jumps near the top of the file.

**Comment by rowe-morehouse** [comment]
Experiencing the same issue with `JSON` files after installing `JSON key-value` package. Sublime 3.2.2. build 3211
