### ISSUE TITLE
Add command that print editorconfig properties

### ISSUE THREAD

**Issue by KindDragon** [sindresorhus/editorconfig-sublime#31]
Add the command that print to the console editorconfig properties for current file

**Comment by Kristinita** [comment]
@sindresorhus , oppose. I don't want to see editorconfig settings every time as I open file of new project. I do not need these messages in the console, they interfere with me. See [**my issue**](https://github.com/sindresorhus/editorconfig-sublime/issues/62) for details.

I think, it would be nice option `"show_settings_in_console"`, with boolean values, but don't show messages by default.

Thanks.
