### ISSUE TITLE
insert_final_newline = false | not working

### ISSUE THREAD

**Issue by jomo** [sindresorhus/editorconfig-sublime#44]
From [the docs](http://editorconfig.org/#supported-properties):

> `insert_final_newline`: set to "true" ensure file ends with a newline when saving
> and "false" to **_ensure it doesn't**_.

As I understand this, it should **remove** final newlines if present. That doesn't happen.

**Comment by jomo** [comment]
Might be a duplicate of #33? not sure.

**Comment by sindresorhus** [comment]
Yes, it probably should, but Sublime doesn't do this, so this plugin will have to remove final newlines manually. PR welcome ;)

**Comment by jtsternberg** [comment]
Pretty please somebody submit a PR. :) Alternatively, @sindresorhus, if you could point out the best way to work on the extension... Working on other's extensions is not something I have tried yet.
