### ISSUE TITLE
Adding the label `snippets` to Package  Control properties

### ISSUE THREAD

**Issue by kipit** [sindresorhus/editorconfig-sublime#52]
Maybe `editorconfig-sublime` deserve [snippets label](https://packagecontrol.io/browse/labels/snippets). Not sure how to purpose this change as a PR, so I ask using a question issue.

**Comment by kipit** [comment]
Also noting there is a singular [snippet label](https://packagecontrol.io/browse/labels/snippet). Not sure about the best option… if any!

**Comment by sindresorhus** [comment]
:+1: Good idea. Can you do a pull request on https://github.com/wbond/package_control_channel, adding it?

**Comment by kipit** [comment]
Thanks, submitted: https://github.com/wbond/package_control_channel/pull/5313
