### ISSUE TITLE
Files with plus signs in names are omitted

### ISSUE THREAD

**Issue by allen-zeng** [sindresorhus/editorconfig-sublime#53]
When a file name contains a plus sign, the plugin doesn't seem to be able to pick it up and apply the styles.

**Comment by kipit** [comment]
Do you have an example of file name? What pattern (between square bracket) do you use?

**Comment by allen-zeng** [comment]
Sorry - this report is actually inaccurate. I am experiencing inconsistent problems though.

Closing this. Will create a new issue when I figure out what the root cause is.
