### ISSUE TITLE
Indentation conversion breaks PHP heredoc blocks

### ISSUE THREAD

**Issue by Loilo** [sindresorhus/editorconfig-sublime#59]
The indentation of heredoc blocks is changed to match the .editorconfig indentation.
Since heredoc blocks are strings this is actually a bug.

**Comment by sindresorhus** [comment]
This plugin just uses the Sublime API to convert the indentation. You would have to report this on the Sublime support forum.

**Comment by Loilo** [comment]
Sounds reasonable.

**Comment by KevinSjoberg** [comment]
@sindresorhus we can close this issue, right?

**Comment by Loilo** [comment]
Since this is not something that lies in the hands of this plugin – yes. I'll close this one.

**Comment by sindresorhus** [comment]
Make sure you reported it here: https://forum.sublimetext.com
