### ISSUE TITLE
TypeError: unhashable type: 'dict',when i install editorconfig plugin in sublime text3

### ISSUE THREAD

**Issue by zhoushirong** [sindresorhus/editorconfig-sublime#60]
When I install editorconfig plugin in sublime text3, it doesn't work.

I found the console log is
`TypeError: unhashable type: 'dict'`

**environment** 
`mac os 10.12.1 python 2.7.10 sublime Text3 build 3126`

**details logs**

`Traceback (most recent call last):File "package_control.package_installer in /Users/zsr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 154, in on_doneFile "package_control.package_disabler in /Users/zsr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 144, in disable_packages File "package_control.settings in /Users/zsr/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 72, in save_list_setting
TypeError: unhashable type: 'dict'
reloading settings Packages/User/Package Control.sublime-settings`

I don't know what happened，is the plugin's problem or myself?

**Comment by sindresorhus** [comment]
That error is coming from Package Control, not this plugin.
