### ISSUE TITLE
cannot exclude files

### ISSUE THREAD

**Issue by phil123456** [sindresorhus/editorconfig-sublime#64]
Hi,

I try to display/edit only js files but it does not work

all files are showing up in the left folders panel

```
# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[{/*.js}]
charset = utf-8
indent_style = space
indent_size = 4
insert_final_newline = true
trim_trailing_whitespace = true
```

sublime text can do it via it's config but I want it to be different from one project to another

```
"file_exclude_patterns":
[
  "*.js"
],
```

thanks

**Comment by sindresorhus** [comment]
That's not how this plugin works. It doesn't ignore it from your sidebar.

**Comment by phil123456** [comment]
is this called editor config ? right ?

**Comment by kipit** [comment]
> is this called editor config ? right ?

Yes @phil123456. So, please, take a look at the [EditorConfig site](http://editorconfig.org/). This project is related to coding style, not UI.
