### ISSUE TITLE
[Feature request] support for `tab_width`

### ISSUE THREAD

**Issue by gucong3000** [sindresorhus/editorconfig-sublime#65]
https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#tab_width

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/editorconfig-sublime/pull/66#issuecomment-294366904

**Comment by gucong3000** [comment]
@sindresorhus 

Please think again. this PR really implements each user can use their own indentation width.

**Comment by gucong3000** [comment]
This is a part of `editorconfig`. We should give users the right to write this option in the configuration file.
