### ISSUE TITLE
trim trailing semicolon

### ISSUE THREAD

**Issue by iseriousnoob** [sindresorhus/editorconfig-sublime#71]
could the extension 

trim_trailing_semicolon

be added?

**Comment by kipit** [comment]
This package handle EditorConfig file format, ans I don't see support for this feature by the EditorConfig file format: http://editorconfig.org/ 
Am I missing something?

**Comment by sindresorhus** [comment]
That's outside the scope of this plugin and EditorConfig as it's language specific.
