### ISSUE TITLE
Convert spaces to tabs in sublime when no .editorconfig file

### ISSUE THREAD

**Issue by mattiasahlsen** [sindresorhus/editorconfig-sublime#74]
Just is in the title: in sublime text, it keeps changing spaces to tabs every time I save the file when I have no .editorconfig. This must be a bug, right?

**Comment by xuhdev** [comment]
Do you have any `.editorconfig` files along the path to the root? For example, `/home/matt/.editorconfig` will affect `/home/matt/fun/*` if no `.editorconfig` file is in `/home/matt/fun`.

**Comment by mattiasahlsen** [comment]
Yes, sorry, my bad, I did.
