### ISSUE TITLE
"Toggle Comment" does not work

### ISSUE THREAD

**Issue by mrmeszaros** [sindresorhus/editorconfig-sublime#75]
I cannot toggle comments in `EditorConfig/EditorConfig` and `EditorConfig/INI` files.

**Comment by sindresorhus** [comment]
What Sublime version? Toggling a comment in a `.editorconfig` file works fine for me. (Sublime 3.1.1)

**Comment by mrmeszaros** [comment]
**Sublime version:** 3.1.1
**OS:** Windows 10

If I also install the **INI** package, the comment toggling starts to work (and uses the `;` character for comments).
If I then disable, it stops working.

Please tell me what other information I can provide to resolve the issue.
