### ISSUE TITLE
For anothe editor?

### ISSUE THREAD

**Issue by Alexey-T** [sindresorhus/editorconfig-sublime#80]
Hi. Nice work. Can I make you some donation to make EditorConfig plugin for CudaText?
http://wiki.freepascal.org/CudaText_API

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in developing it for other editors. You could try asking in https://github.com/editorconfig/editorconfig/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
