### ISSUE TITLE
Package Info unavailable

### ISSUE THREAD

**Issue by LuminousPath** [sindresorhus/editorconfig-sublime#89]
Not sure if you're aware but the Package Repo seems to be having trouble pulling the package info for this.

Related or not, I can't seem to pull this package either.

![image](https://user-images.githubusercontent.com/374740/91166003-9eea4b00-e70c-11ea-8d3a-cb911d4eb793.png)

**Comment by sindresorhus** [comment]
That's a problem with PackageControl.
