### ISSUE TITLE
Package control reporting EditorConfig as missing

### ISSUE THREAD

**Issue by tuzemec** [sindresorhus/editorconfig-sublime#92]
[Package Control](https://packagecontrol.io/packages/EditorConfig) is reporting this plugin as missing.

> Package info was unavailable last time crawler ran. Error downloading repository. HTTP error 404 downloading https://api.github.com/repos/sindresorhus/editorconfig-sublime/commits?sha=master&per_page=1.

**Comment by sindresorhus** [comment]
https://github.com/wbond/package_control_channel/pull/8173
